JobFolioProject/JobFolio

- .gitignore
> 브랜치 풀 요청 테스트입니다.

- react-project/README.md
> 커밋test해봄수경

- jobfollio/src/main/java/com/happyjob/jobfolio/service/chatgpt/ChatgptService.java
- jobfollio/src/main/resources/application.properties
기존properties파일과 secret-properties파일 분리하여 키값 깃허브에 노출되지 않도록 변경, secret-properties파일 import완료
> [2025-06-10] 엄희윤-properties파일 설정

- react-project/src/components/resume/Resume.jsx
- react-project/src/components/resume/ResumeSidebar.jsx
- react-project/src/css/resume/Resume.css
- react-project/src/css/resume/ResumeSidebar.css
> [2025-06-10]임수경--resume.jsx resume sidebar수정

- react-project/src/App.js
> [20250611]이현명-app.js업데이트

- react-project/src/components/resume/Resume.jsx
- react-project/src/components/resume/ResumeModify.jsx
url 통일 및 component 연결, 중복 div 삭제
> [2025-06-11] 엄희윤 - 이력서 페이지 수정

- jobfollio/src/main/java/com/happyjob/jobfolio/controller/resume/ResumeController.java
- jobfollio/src/main/java/com/happyjob/jobfolio/service/resume/ResumeService.java
> [2025-06-11]우희민- Resume백단생성

- jobfollio/src/main/java/com/happyjob/jobfolio/controller/resume/ResumeController.java
- react-project/src/components/resume/Resume.jsx
- react-project/src/css/resume/Resume.css
> [2025-06-11]우희민-resume업데이트

- react-project/src/components/admin/adminComponents/FaqManagement.jsx
- react-project/src/components/admin/adminComponents/FaqManagement_detail.jsx
- react-project/src/components/admin/adminComponents/InfoManagement.jsx
- react-project/src/components/admin/adminComponents/InfoManagement_detail.jsx
- react-project/src/css/admin/adminComponents/FaqManagement.css
- react-project/src/css/admin/adminComponents/FaqManagement_detail.css
- react-project/src/css/admin/adminComponents/InfoManagement.css
FAQ 모달창 생성 및 css 적용
이용안내등록 모달창 생성 및 css 적용
FAQ 창 생성 및 css 적용
> [2025-06-11] 이채은 게시판페이지 작성 및 수정

- jobfollio/src/main/java/com/happyjob/jobfolio/controller/resume/ResumeController.java
- jobfollio/src/main/java/com/happyjob/jobfolio/service/resume/ResumeService.java
> [2025-06-12]우희민-이력서작성백앤드

- jobfollio/src/main/java/com/happyjob/jobfolio/controller/notice/BoardInfoController.java
- jobfollio/src/main/java/com/happyjob/jobfolio/repository/notice/BoardInfoRepository.java
- jobfollio/src/main/java/com/happyjob/jobfolio/service/NoticeService/BoardInfoService.java
- jobfollio/src/main/java/com/happyjob/jobfolio/vo/notice/BoardInfoVo.java
- jobfollio/src/main/resources/mappers/notice/NoticeMapper.xml
- react-project/src/components/admin/adminComponents/InfoManagement.jsx
- react-project/src/components/admin/adminComponents/InfoManagement_detail.jsx
- react-project/src/components/common/Pagination.jsx
- react-project/src/components/community/CommuInfo.jsx
- react-project/src/css/common/Pagination.css
pagination.jsx common에 생성
페이지에서 이용안내 등록하면 db 연동됨
> [2025-06-12] 이채은 pagination, 관리자페이지에서 이용안내 등록

- jobfollio/src/main/java/com/happyjob/jobfolio/controller/resume/ResumeController.java
- jobfollio/src/main/java/com/happyjob/jobfolio/repository/resume/ResumeMapper.java
- jobfollio/src/main/java/com/happyjob/jobfolio/service/resume/ResumeService.java
- jobfollio/src/main/resources/mappers/resume/ResumeMapper.xml
- react-project/package-lock.json
- react-project/src/components/resume/Resume.jsx
> [2025-06-12]우희민-이력서저장

- jobfollio/src/main/java/com/happyjob/jobfolio/controller/mypage/MypageController.java
- jobfollio/src/main/java/com/happyjob/jobfolio/repository/mypage/MypageMapper.java
- jobfollio/src/main/java/com/happyjob/jobfolio/vo/mypage/CareerAllDto.java
- jobfollio/src/main/java/com/happyjob/jobfolio/vo/mypage/CareerHistoryVO.java
- jobfollio/src/main/java/com/happyjob/jobfolio/vo/mypage/CertificateVO.java
- jobfollio/src/main/java/com/happyjob/jobfolio/vo/mypage/EduInfoVO.java
- jobfollio/src/main/java/com/happyjob/jobfolio/vo/mypage/LanguageSkillVO.java
- jobfollio/src/main/java/com/happyjob/jobfolio/vo/mypage/SkillVO.java
- jobfollio/src/main/resources/mappers/mypage/MypageMapper.xml
- react-project/src/components/user/myPageComponent/CareerHistorySection.jsx
- react-project/src/components/user/myPageComponent/CertificateSection.jsx
- react-project/src/components/user/myPageComponent/EducationSection.jsx
- react-project/src/components/user/myPageComponent/LanguageSection.jsx
- react-project/src/components/user/myPageComponent/MyCareer.jsx
- react-project/src/components/user/myPageComponent/SkillSection.jsx
> 마이페이지 VO 필드 수정

- jobfollio/src/main/java/com/happyjob/jobfolio/controller/resume/ResumeController.java
- jobfollio/src/main/resources/mappers/resume/ResumeMapper.xml
> [2025-06-12]우희민-이력서세팅

- react-project/src/components/admin/axiosAdmin.js
- react-project/src/components/common/MenuBar.jsx
- react-project/src/components/user/join/LoginForm.jsx
- react-project/src/components/user/myPageComponent/SideBar.jsx
로그인 후 session에 json 데이터 저장, 각 페이지 권한 사용시 user 변수의 userType 사용하도록 변경
> [2025-06-12] 엄희윤 로그인 정보 Json파일로 변경

- react-project/package-lock.json
- react-project/public/resources/html/example.html
- react-project/src/components/resume/ResumeEditModal.jsx
- react-project/src/components/resume/ResumeModify.jsx
- react-project/src/css/resume/PrettyBtn.css
- react-project/src/css/resume/ResumeEditModal.css
> ResumeEditModal 수정

- jobfollio/src/main/java/com/happyjob/jobfolio/controller/resume/ResumeController.java
> [2025-06-12]우희민-이력서작성수정

- jobfollio/src/main/java/com/happyjob/jobfolio/controller/notice/BoardInfoController.java
- jobfollio/src/main/java/com/happyjob/jobfolio/repository/notice/BoardInfoRepository.java
- jobfollio/src/main/java/com/happyjob/jobfolio/service/NoticeService/BoardInfoService.java
- jobfollio/src/main/java/com/happyjob/jobfolio/vo/notice/BoardInfoVo.java
- jobfollio/src/main/resources/mappers/notice/NoticeMapper.xml
- react-project/package-lock.json
- react-project/src/components/admin/adminComponents/InfoManagement.jsx
- react-project/src/components/admin/adminComponents/InfoManagement_detail.jsx
이용안내 등록 버튼 누르고 등록모달창에서 글 작성 후 저장가능 + DB연동
TITLE 제목 누르고 수정모달창에서 글 수정 후 저장가능 + DB연동
수정, 등록, 삭제시 화면에서 변경
우선순위(priority) 관리자 페이지에서 직접 변경 가능 + DB연동
우선순위 기준으로 내림차순 후 화면에 보여지게 설정
> [2025-06-12] 이채은 관리자 이용안내 페이지

- jobfollio/src/main/java/com/happyjob/jobfolio/controller/admin/AdminController.java
- jobfollio/src/main/java/com/happyjob/jobfolio/controller/mypage/MypageController.java
- jobfollio/src/main/java/com/happyjob/jobfolio/repository/mypage/MypageMapper.java
- jobfollio/src/main/java/com/happyjob/jobfolio/service/mypage/MypageService.java
- jobfollio/src/main/java/com/happyjob/jobfolio/vo/usermgr/UserModel.java
- jobfollio/src/main/resources/mappers/mypage/MypageMapper.xml
- react-project/src/components/user/myPageComponent/UserInfo.jsx
회원정보  조회 및 화면에 표시, 데이터 입력, 취소시 데이터 다시 불러오기 기능까지 완료, 수정 DB연동 x
> [2025-06-12] 엄희윤 마이페이지 회원정보

- react-project/src/components/resume/Resume.jsx
- react-project/src/components/resume/TemplateSelection.jsx
TemplateSelection.jsx 만듦 Resume.jsx적용
> [2025-06-13]임수경 TemplateSelection.jsx 만듦 Resume.jsx적용

- jobfollio/src/main/java/com/happyjob/jobfolio/controller/resume/ResumeController.java
- jobfollio/src/main/java/com/happyjob/jobfolio/repository/resume/ResumeMapper.java
- jobfollio/src/main/java/com/happyjob/jobfolio/service/resume/ResumeService.java
- jobfollio/src/main/resources/mappers/resume/ResumeMapper.xml
> [2025-06-13]우희민-이력서 저장

- jobfollio/src/main/resources/application.properties
- react-project/src/components/user/Login.jsx
- react-project/src/components/user/myPageComponent/UserInfo.jsx
- react-project/src/css/user/myPageComponent/UserInfo.css
DB 테이블 완성 후 DB 재연동, 로그인 및 테이블, 마이페이지 작동 확인 후 커밋
myPage 수정시 CSS 변하도록 추가
> [2025-06-13] 엄희윤 DB 재연동 및 myPage 작업

- react-project/package-lock.json
- react-project/package.json
- react-project/public/test.html
- react-project/src/components/resume/Resume.jsx
- react-project/src/components/resume/TemplateSelection.jsx
- react-project/src/components/resume/TemplateSlider.jsx
- react-project/src/css/resume/TemplateSlider.css
임수경-TemplateSlider구현 및 TemplateSelection으로 템플렛 조회 만듦.
TemplateSlider.css
TemplateSlider.jsx 템플렛 넘기기.
TemplateSelection.jsx 템플렛 리스트 조회, iframe사용
> [2025-06-16]임수경-TemplateSlider구현 및 TemplateSelection으로 템플렛 조회 만듦.

- jobfollio/src/main/java/com/happyjob/jobfolio/controller/admin/AdminCommunityController.java
- jobfollio/src/main/java/com/happyjob/jobfolio/controller/community/CommunityController.java
- jobfollio/src/main/java/com/happyjob/jobfolio/repository/admin/AdminCommunityMapper.java
- jobfollio/src/main/java/com/happyjob/jobfolio/service/admin/AdminCommunityService.java
- jobfollio/src/main/resources/mappers/admin/AdminCommunityMapper.xml
- jobfollio/src/main/resources/mappers/community/CommunityMapper.xml
- react-project/src/components/admin/adminComponents/NoticeManagement.jsx
- react-project/src/components/admin/adminComponents/NoticeManagement_detail.jsx
- react-project/src/css/admin/adminComponents/NoticeManagement_detail.css
> [2025-06-16] 김용현 공지사항 기능

- jobfollio/src/main/java/com/happyjob/jobfolio/controller/join/UserController.java
- jobfollio/src/main/java/com/happyjob/jobfolio/controller/mypage/MypageController.java
- jobfollio/src/main/java/com/happyjob/jobfolio/repository/mypage/MypageMapper.java
- jobfollio/src/main/java/com/happyjob/jobfolio/service/mypage/MypageService.java
- jobfollio/src/main/resources/mappers/mypage/MypageMapper.xml
- react-project/src/components/user/Login.jsx
- react-project/src/components/user/myPageComponent/UserInfo.jsx
- react-project/src/css/user/myPageComponent/UserInfo.css
마이페이지 수정하기 버튼 누를시 css적용, 업데이트 쿼리 적용 완료
> [2025-06-16] 엄희윤 마이페이지 수정 완료

- jobfollio/pom.xml
- jobfollio/src/main/java/com/happyjob/jobfolio/controller/join/UserController.java
회원탈퇴시 아이디 비밀번호 사용을 위해 BCrypt 사용, 추가
> [2025-06-16] 엄희윤 Bcrypt 추가

- react-project/src/components/user/join/JoinForm.jsx
> Update JoinForm.jsx to correct comment typo in detailAddress state

- jobfollio/src/main/java/com/happyjob/jobfolio/controller/notice/BoardInfoController.java
- jobfollio/src/main/java/com/happyjob/jobfolio/repository/notice/BoardInfoRepository.java
- jobfollio/src/main/java/com/happyjob/jobfolio/service/NoticeService/BoardInfoService.java
- jobfollio/src/main/java/com/happyjob/jobfolio/vo/notice/BoardInfoVo.java
- jobfollio/src/main/resources/mappers/notice/NoticeMapper.xml
- react-project/src/components/admin/adminComponents/FaqManagement.jsx
- react-project/src/components/admin/adminComponents/InfoManagement.jsx
- react-project/src/components/admin/adminComponents/InfoManagement_detail.jsx
- react-project/src/components/community/CommuFaq.jsx
- react-project/src/components/community/CommuInfo.jsx
- react-project/src/css/admin/adminComponents/InfoManagement.css
- react-project/src/css/community/CommuFaq.css
- react-project/src/css/community/CommuInfo.css
우선순위 오류들 해결
사용자 커뮤니티 페이지 css 수정
> [2025-06-16] 이채은 관리자페이지 우선순위

- jobfollio/src/main/java/com/happyjob/jobfolio/controller/resume/ResumeController.java
- jobfollio/src/main/java/com/happyjob/jobfolio/repository/resume/ResumeMapper.java
- jobfollio/src/main/java/com/happyjob/jobfolio/service/resume/ResumeService.java
- jobfollio/src/main/resources/mappers/resume/ResumeMapper.xml
- react-project/src/components/user/myPageComponent/ResumeDetail.jsx
> [2025-06-16]우희민-이력서삭제기능

- jobfollio/src/main/java/com/happyjob/jobfolio/controller/resume/ResumeController.java
- jobfollio/src/main/java/com/happyjob/jobfolio/repository/resume/ResumeMapper.java
- jobfollio/src/main/java/com/happyjob/jobfolio/service/resume/ResumeService.java
- jobfollio/src/main/resources/mappers/resume/ResumeMapper.xml
- react-project/package-lock.json
- react-project/package.json
- react-project/public/resources/html/example.html
- react-project/src/components/common/Loading.jsx
- react-project/src/components/resume/CareerSectionModify.jsx
- react-project/src/components/resume/EduSectionModify.jsx
- react-project/src/components/resume/ResumeEditModal.jsx
- react-project/src/components/resume/ResumeModify.jsx
- react-project/src/css/resume/ResumeEditModal.css
- react-project/src/css/resume/ResumeModify.css
1. 이력서 수정 클릭시 해당 유저가 작성한 이력서 목록 우선순위로 출력
2. 해당 이력서 클릭시 파일경로를  /resume/selectOneResume에 전달해  해당 파일의 html코드를 전달 받음
3. Ai Comment 기능
> [2025-06-17]이현명 - 이력서 수정 업데이트

- react-project/src/components/admin/AdminPage.jsx
> [2025-06-17] 엄희윤 관리자페이지 수정

- react-project/src/components/admin/AdminPage.jsx
- react-project/src/components/user/myPageComponent/PostLike.jsx
- react-project/src/components/user/myPageComponent/UserInfo.jsx
spring Security 업데이트에 대하여 해당 부분 코드 모두 수정, 적용 완료하였습니다. 동작 확인 후 푸쉬합니다
> [2025-06-17] 엄희윤 security관련 axios 전체 수정 완료, 사용가능

- jobfollio/src/main/java/com/happyjob/jobfolio/config/SecurityConfig.java
- jobfollio/src/main/java/com/happyjob/jobfolio/controller/resume/ResumeController.java
- jobfollio/src/main/java/com/happyjob/jobfolio/vo/resume/ResumeInfoVO.java
- jobfollio/src/main/resources/mappers/resume/ResumeMapper.xml
- react-project/src/components/admin/adminComponents/FaqManagement_detail.jsx
- react-project/src/components/user/myPageComponent/ResumeDetail.jsx
> [2025-06-17]우희민-axios 고친부분

- jobfollio/src/main/java/com/happyjob/jobfolio/config/SecurityConfig.java
> Update SecurityConfig to permit access to resume-related API endpoints

- jobfollio/src/main/java/com/happyjob/jobfolio/controller/mainProduct/mainProductController.java
- jobfollio/src/main/java/com/happyjob/jobfolio/controller/pay/PayController.java
- jobfollio/src/main/java/com/happyjob/jobfolio/controller/product/ProductController.java
- jobfollio/src/main/java/com/happyjob/jobfolio/repository/pay/PayMapper.java
- jobfollio/src/main/java/com/happyjob/jobfolio/service/pay/PayService.java
- react-project/src/components/admin/adminComponents/SubscriptManagement.jsx
- react-project/src/components/admin/adminComponents/SubscriptManagement_detail.jsx
- react-project/src/components/pay/Payment.jsx
> 결제 api 연동중

- jobfollio/src/main/java/com/happyjob/jobfolio/controller/resume/ResumeController.java
- react-project/src/App.js
- react-project/src/components/user/myPageComponent/ResumeDetail.jsx
- react-project/src/context/ResumeEditContext.jsx
> [2025-06-18]우희민-마이페이지 이력서 내역

- jobfollio/src/main/java/com/happyjob/jobfolio/controller/mypage/MypageController.java
- jobfollio/src/main/java/com/happyjob/jobfolio/controller/resume/ResumeController.java
- jobfollio/src/main/java/com/happyjob/jobfolio/vo/mypage/CareerAllDto.java
- jobfollio/src/main/java/com/happyjob/jobfolio/vo/mypage/EduInfoVO.java
- jobfollio/src/main/java/com/happyjob/jobfolio/vo/mypage/SkillVO.java
- jobfollio/src/main/java/com/happyjob/jobfolio/vo/resume/AiResumeGenerateVO.java
- jobfollio/src/main/java/com/happyjob/jobfolio/vo/resume/ResumeInfoVO.java
- jobfollio/src/main/java/com/happyjob/jobfolio/vo/system/CommcodeModel.java
- jobfollio/src/main/resources/mappers/mypage/MypageMapper.xml
- react-project/public/resources/html/test3.html
- react-project/src/components/resume/Resume.jsx
- react-project/src/components/resume/ResumeAiCovLetter.jsx
- react-project/src/components/resume/TemplateSelection.jsx
- react-project/src/components/resume/TemplateSlider.jsx
- react-project/src/css/resume/Resume.css
> [2025-06-18]임수경 재업로드 skill조회부분 수정  수정

- react-project/src/components/resume/ResumeModify.jsx
- react-project/src/components/user/myPageComponent/ResumeDetail.jsx
- react-project/src/context/ResumeEditContext.jsx
> [2025-06-18]우희민 이력서내역 수정본

- jobfollio/src/main/resources/mappers/notice/NoticeMapper.xml
- react-project/src/components/community/CommuInfo.jsx
- react-project/src/css/community/CommuInfo.css
css 수정
desc 삭제 우선순위 오름차순
관리자페이지에서 이용안내등록시 줄바꿈 처리가능
> [2025-06-18] 이채은 사용자 이용안내 페이지

- jobfollio/src/main/java/com/happyjob/jobfolio/controller/join/UserController.java
- jobfollio/src/main/java/com/happyjob/jobfolio/security/JwtAuthenticationFilter.java
- jobfollio/src/main/java/com/happyjob/jobfolio/security/JwtTokenProvider.java
- jobfollio/src/main/java/com/happyjob/jobfolio/security/UserPrincipal.java
- jobfollio/src/main/java/com/happyjob/jobfolio/service/join/UserService.java
- react-project/src/components/common/PrivateRoute.jsx
- react-project/src/context/AuthContext.jsx
결제/미결제 구분하기 위해 user table의 expire_days를 토큰 및 로그인 시 userData에 추가해서 적용
> [2025-06-18] 이현명 - 회원 미결제시 이력서 메뉴 제한 설정

- react-project/src/components/admin/adminComponents/ResumeManagement.jsx
- react-project/src/css/admin/adminComponents/ResumeManagement.css
> [2025-06-18] 이채은 관리자 이력서 페이지

- jobfollio/src/main/java/com/happyjob/jobfolio/controller/resume/ResumeController.java
- jobfollio/src/main/java/com/happyjob/jobfolio/repository/resume/ResumeMapper.java
- jobfollio/src/main/java/com/happyjob/jobfolio/service/resume/ResumeService.java
- jobfollio/src/main/java/com/happyjob/jobfolio/vo/resume/ResumeInfoVO.java
- jobfollio/src/main/resources/mappers/resume/ResumeMapper.xml
- react-project/src/components/community/CommuResume.jsx
- react-project/src/css/community/CommuResume.css
> [2025-06-18] 엄희윤 이력서게시판 페이지 좋아요

- react-project/src/components/community/CommuResume.jsx
- react-project/src/css/community/CommuResume.css
> [2025-06-18] 엄희윤 이력서페이지 팝업

- jobfollio/src/main/java/com/happyjob/jobfolio/controller/pay/PayController.java
- jobfollio/src/main/java/com/happyjob/jobfolio/repository/pay/PayMapper.java
- jobfollio/src/main/java/com/happyjob/jobfolio/service/pay/PayService.java
- jobfollio/src/main/resources/mappers/pay/PayMapper.xml
- react-project/src/components/admin/adminComponents/SubscriptManagement.jsx
- react-project/src/components/admin/adminComponents/SubscriptStatus.jsx
- react-project/src/components/pay/Payment.jsx
> pr 안되서 재갱신

- jobfollio/src/main/java/com/happyjob/jobfolio/controller/resume/ResumeController.java
- jobfollio/src/main/java/com/happyjob/jobfolio/repository/resume/ResumeMapper.java
- jobfollio/src/main/java/com/happyjob/jobfolio/service/resume/ResumeService.java
- jobfollio/src/main/resources/mappers/resume/ResumeMapper.xml
- react-project/src/components/admin/adminComponents/ResumeManagement.jsx
- react-project/src/css/admin/adminComponents/ResumeManagement.css
관리자 이력서 페이지에서 선택항목 삭제가능
작성자, 이력서 번호, 제목 으로 검색 기능
> [2025-06-19] 이채은 관리자 이력서 페이지

- jobfollio/src/main/java/com/happyjob/jobfolio/controller/resume/ResumeController.java
- react-project/src/components/resume/Resume.jsx
> [2025-06-20]우희민-PDF저장 로직

- react-project/package-lock.json
- react-project/package.json
- react-project/src/components/Main.jsx
- react-project/src/components/mainPage/Chat.jsx
> [2025-06-20] 엄희윤 관리자 채팅 구현

- react-project/src/components/mainPage/Main3rd.jsx
- react-project/src/components/resume/Resume.jsx
- react-project/src/components/resume/TemplateSelection.jsx
- react-project/src/components/resume/TemplateSlider.jsx
> [2025-06-20]우희민-수정중

- react-project/src/components/admin/adminComponents/ResumeManagement.jsx
- react-project/src/components/community/CommuResume.jsx
- react-project/src/components/mainPage/Chat.jsx
- react-project/src/components/mainPage/Main2nd.jsx
- react-project/src/components/mainPage/Main3rd.jsx
- react-project/src/components/mainPage/MainEmail.jsx
- react-project/src/components/mainPage/MainPage.jsx
- react-project/src/css/admin/adminComponents/ResumeManagement.css
- react-project/src/css/community/CommuResume.css
- react-project/src/css/mainPage/Main2nd.css
- react-project/src/css/mainPage/Main3rd.css
- react-project/src/css/resume/TemplateSlider.css
> [2025-06-20] 엄희윤 css 중복선택자 수정

- jobfollio/src/main/java/com/happyjob/jobfolio/service/resume/ResumeService.java
- react-project/src/components/resume/Resume.jsx
- react-project/src/components/resume/ResumeModal.jsx
- react-project/src/components/resume/TemplateSlider.jsx
> [2025-06-20]임수경 templateSlider.jsx, template 정보 넘김, 모달창 구현중.

- jobfollio/src/main/java/com/happyjob/jobfolio/controller/resume/ResumeController.java
- react-project/src/components/resume/ResumePreviewModal.jsx
- react-project/src/components/resume/TemplateSlider.jsx
- react-project/src/css/resume/ResumePreviewModal.css
- react-project/src/css/resume/TemplateSlider.css
> [2025-06-20]우희민-이력서 미리보기 및 저장

- jobfollio/src/main/java/com/happyjob/jobfolio/controller/interview/InterviewController.java
- jobfollio/src/main/java/com/happyjob/jobfolio/service/interview/InterviewService.java
- react-project/src/components/interview/Interview.jsx
- react-project/src/css/interview/Interview.css
> [2025-06-20] 김용현 면접연습 페이지

- jobfollio/src/main/java/com/happyjob/jobfolio/controller/resume/ResumeController.java
- jobfollio/src/main/java/com/happyjob/jobfolio/repository/resume/ResumeMapper.java
- jobfollio/src/main/java/com/happyjob/jobfolio/service/resume/ResumeService.java
- jobfollio/src/main/resources/mappers/resume/ResumeMapper.xml
- react-project/src/components/user/myPageComponent/PostLike.jsx
- react-project/src/components/user/myPageComponent/ResumeDetail.jsx
- react-project/src/css/resume/ResumeModify.css
- react-project/src/css/user/myPageComponent/ResumeDetail.css
> [2025-06-20]우희민-이력서내역 페이징처리

- react-project/src/components/resume/TemplateSlider.jsx
> conflict recoverd

- react-project/src/components/resume/Resume.jsx
- react-project/src/components/resume/TemplateSlider.jsx
- react-project/src/css/resume/PrettyBtn.css
- react-project/src/css/resume/Resume.css
이력서 부분 수정했음. 어학, 자격증 추가 및 css 수정
> [2025-06-21]임수경 이력서 부분 수정했음. 어학, 자격증 추가 및 css 수정

- react-project/src/components/community/CommuResume.jsx
- react-project/src/css/community/CommuResume.css
- react-project/src/css/interview/Interview.css
> [2025-06-23] 김용현 커뮤니티 이력서 페이지 오류 해결

- react-project/src/App.js
- react-project/src/css/mainPage/MainEmail.css
> [2025-06-24] 엄희윤 페이지 최상단으로 정렬

- jobfollio/src/main/java/com/happyjob/jobfolio/controller/resume/ResumeController.java
- jobfollio/src/main/resources/mappers/resume/ResumeMapper.xml
- react-project/src/components/admin/adminComponents/ResumeManagement.jsx
- react-project/src/components/community/CommuResume.jsx
- react-project/src/css/admin/adminComponents/ResumeManagement.css
- react-project/src/css/community/CommuResume.css
이력서 관리 페이지 이력서 조회 및 수정, 공개여부 부분 수정
> [2025-06-24] 엄희윤 이력서 관리페이지 수정

- jobfollio/src/main/java/com/happyjob/jobfolio/vo/resume/ResumeInfoVO.java
- jobfollio/src/main/resources/mappers/resume/ResumeMapper.xml
- react-project/src/components/community/CommuResume.jsx
> [2025-06-24] 엄희윤 좋아요 갯수 조회 추가

- react-project/src/components/community/CommuResume.jsx
- react-project/src/css/community/CommuResume.css
> 좋아요 갯수 위치조정

- jobfollio/src/main/resources/mappers/resume/ResumeMapper.xml
- react-project/src/components/user/myPageComponent/PostLike.jsx
- react-project/src/css/community/CommuResume.css
- react-project/src/css/user/myPageComponent/PostLike.css
> [2025-06-24] 엄희윤 마이페이지 좋아요목록

- jobfollio/src/main/resources/mappers/resume/ResumeMapper.xml
- react-project/src/components/admin/adminComponents/ResumeManagement.jsx
- react-project/src/css/admin/adminComponents/ResumeManagement.css
사용자 커뮤니티 이력서 좋아요 많은순서부터 보여주기 -> 좋아요 수 같을 시 최신순
관리자페이지 이력서 쪽 검색버튼 삭제 (없어도 검색됨)
관리자 이력서 페이지 -> 좋아요순 정렬, 최신순 정렬 가능
> [2025-06-24] 이채은 관리자, 사용자커뮤니티 ( 이력서 페이지 )

- react-project/src/css/community/CommuNotice.css
- react-project/src/css/community/CommuNotice_detail.css
> [2025-06-25] 김용현 공지사항 페이지 CSS 수정

- react-project/src/components/admin/adminComponents/ResumeManagement.jsx
- react-project/src/css/admin/adminComponents/ResumeManagement.css
checkbox 클릭 시 오픈 모달 차단
iframe 클릭 시 오픈 모달 생성
> [2025-06-25] 이채은 관리자 이력서 페이지

- react-project/src/components/admin/adminComponents/SubscriptManagement_detail.jsx
> 이용권 수정시 데이터타입 오류 수정

- react-project/src/components/admin/adminComponents/NoticeManagement.jsx
- react-project/src/components/interview/Interview.jsx
- react-project/src/css/admin/adminComponents/NoticeManagement_detail.css
> [2025-06-26] 김용현 단위테스트 중 발견한 오류 수정

- react-project/src/components/admin/adminComponents/TempManModal.jsx
- react-project/src/components/admin/adminComponents/TempModiModal.jsx
- react-project/src/components/admin/adminComponents/TemplateManagement.jsx
- react-project/src/components/resume/Resume.jsx
- react-project/src/css/admin/adminComponents/TempManModal.css
- react-project/src/css/admin/adminComponents/TemplateManagement.css
- react-project/src/css/common/Calendar.css
- react-project/src/css/resume/Resume.css
임수경 스킬부분 마무리, 이력서작성 페이지, 관리자페이지 css 마무리
> [2025-06-26]임수경 스킬부분 마무리, 이력서작성 페이지, 관리자페이지 css 마무리

- react-project/src/css/user/myPageComponent/SideBar.css
> 마이페이지 사이드바 공백 수정

- react-project/src/components/resume/Resume.jsx
> [2025-06-27]임수경 resume.jsx 버그 수정 완료.

- react-project/src/components/admin/adminComponents/GroupManagement.jsx
- react-project/src/css/admin/adminComponents/GroupManagement.css
> [2025-06-27] 김용현 공통 코드 관리 CSS 조정
